# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-09 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('prof_last', models.CharField(max_length=30)),
                ('prof_first', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=30)),
                ('credits', models.CharField(max_length=30)),
                ('course_level', models.CharField(choices=[('D', 'Developmental'), ('U', 'Undergraduate'), ('G', 'Graduate')], max_length=1)),
                ('year', models.CharField(max_length=4)),
                ('term', models.CharField(choices=[('FA', 'Fall'), ('WI', 'Winter'), ('SP', 'Spring'), ('SU', 'Summer')], max_length=2)),
                ('rate_my_prof_url', models.URLField(max_length=500)),
                ('pdf_doc', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
