# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-09 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='country',
        ),
    ]
